PHY_CH = [
    "Chapter 1: Units and Measurements",
    "Chapter 2: Motion in a Straight Line",
    "Chapter 3: Motion in a Plane",
    "Chapter 4: Laws of Motion",
    "Chapter 5: Work, Energy, and Power",
    "Chapter 6: System of Particles and Rotational Motion",
    "Chapter 7: Gravitation",
    "Chapter 8: Mechanical Properties of Solids",
    "Chapter 9: Mechanical Properties of Fluids",
    "Chapter 10: Thermal Properties of Matter",
    "Chapter 11: Thermodynamics",
    "Chapter 12: Kinetic Theory",
    "Chapter 13: Oscillations",
    "Chapter 14: Wave",
]

CHEM_CH =[
    "Chapter 1: Some Basic Concepts of Chemistry",
    "Chapter 2: Structure of Atom",
    "Chapter 3: Classification of Elements and Periodicity in Properties",
    "Chapter 4: Chemical Bonding and Molecular Structure",
    "Chapter 5: States of Matter",
    "Chapter 6: Chemical Thermodynamics",
    "Chapter 7: Equilibrium",
    "Chapter 8: Redox Reactions",
    "Chapter 9: Hydrogen",
    "Chapter 10: The s-Block Elements",
    "Chapter 11: Some p-Block Elements",
    "Chapter 12: Organic Chemistry – Some Basic Principles and Techniques",
    "Chapter 13: Hydrocarbons",
    "Chapter 14: Environmental Chemistry",
]

MATHS_CH =[
    "Chapter 1: Sets",
    "Chapter 2: Relations and Functions",
    "Chapter 3: Trigonometric Functions",
    "Chapter 4: Complex Numbers and Quadratic Equations",
    "Chapter 5: Linear Inequalities",
    "Chapter 6: Permutations and Combinations",
    "Chapter 7: Binomial Theorem",
    "Chapter 8: Sequences and Series",
    "Chapter 9: Straight Lines",
    "Chapter 10: Conic Sections",
    "Chapter 11: Introduction to Three Dimensional Geometry",
    "Chapter 12: Limits and Derivatives",
    "Chapter 13: Statistics",
    "Chapter 14: Probability",
]